"use server";

import { revalidatePath } from "next/cache";

import { getDb } from "@/db";
import { describeDatabaseError } from "@/db/types";
import { authorize } from "@/features/auth/access";
import type { ActionResult } from "@/lib/action-result";
import { routes } from "@/lib/site";
import * as service from "./ideas";
import { ideaKindLabels } from "./model";
import { ideaIdSchema, ideaInputSchema, ideaKindSchema } from "./schemas";

export type IdeaActionResult = ActionResult & { id?: string };

const invalid: ActionResult = { ok: false, message: "That request was not valid." };
// The same answer whether the idea is missing or belongs to someone else.
const missing: ActionResult = { ok: false, message: "That idea no longer exists." };

function firstIssue(error: { issues: { message: string }[] }, fallback: string): ActionResult {
  return { ok: false, message: error.issues[0]?.message ?? fallback };
}

function refresh(id?: string) {
  revalidatePath(routes.library);
  revalidatePath(routes.dashboard);
  if (id) revalidatePath(`${routes.library}/${id}`);
}

/*
 * Every action authorises itself when it runs and takes the owner from the
 * session. Nothing in the input can name an owner, and the schema drops any
 * key it does not know.
 */

/** Saves a new idea. `id` may be generated by the browser so a retry cannot save it twice. */
export async function createIdea(input: unknown, id?: unknown): Promise<IdeaActionResult> {
  const actor = await authorize("active");
  if (!actor.ok) return actor;

  const parsed = ideaInputSchema.safeParse(input);
  if (!parsed.success) return firstIssue(parsed.error, "That idea could not be saved.");
  const ideaId = id === undefined ? undefined : ideaIdSchema.safeParse(id);
  if (ideaId && !ideaId.success) return invalid;

  try {
    const idea = await service.createIdea(getDb(), actor.user.id, parsed.data, ideaId?.data);
    if (!idea) return { ok: false, message: "The idea could not be saved. Try again." };
    refresh();
    return { ok: true, message: "Saved to your library.", id: idea.id };
  } catch (error) {
    console.error("Idea create failed:", describeDatabaseError(error));
    return { ok: false, message: "The idea could not be saved. Try again." };
  }
}

export async function updateIdea(id: unknown, input: unknown): Promise<ActionResult> {
  const actor = await authorize("active");
  if (!actor.ok) return actor;

  const ideaId = ideaIdSchema.safeParse(id);
  if (!ideaId.success) return invalid;
  const parsed = ideaInputSchema.safeParse(input);
  if (!parsed.success) return firstIssue(parsed.error, "Those changes could not be saved.");

  try {
    const idea = await service.updateIdea(getDb(), actor.user.id, ideaId.data, parsed.data);
    if (!idea) return missing;
  } catch (error) {
    console.error("Idea update failed:", describeDatabaseError(error));
    return { ok: false, message: "Your changes could not be saved. Try again." };
  }
  refresh(ideaId.data);
  return { ok: true, message: "Changes saved." };
}

export async function changeIdeaKind(id: unknown, kind: unknown): Promise<ActionResult> {
  const actor = await authorize("active");
  if (!actor.ok) return actor;

  const ideaId = ideaIdSchema.safeParse(id);
  const parsed = ideaKindSchema.safeParse(kind);
  if (!ideaId.success || !parsed.success) return invalid;

  try {
    const idea = await service.setIdeaKind(getDb(), actor.user.id, ideaId.data, parsed.data);
    if (!idea) return missing;
  } catch (error) {
    console.error("Idea reclassification failed:", describeDatabaseError(error));
    return { ok: false, message: "The idea could not be reclassified. Try again." };
  }
  refresh(ideaId.data);
  return { ok: true, message: `Now filed as: ${ideaKindLabels[parsed.data]}.` };
}

export async function deleteIdea(id: unknown): Promise<ActionResult> {
  const actor = await authorize("active");
  if (!actor.ok) return actor;

  const ideaId = ideaIdSchema.safeParse(id);
  if (!ideaId.success) return invalid;

  try {
    if (!(await service.deleteIdea(getDb(), actor.user.id, ideaId.data))) return missing;
  } catch (error) {
    console.error("Idea delete failed:", describeDatabaseError(error));
    return { ok: false, message: "The idea could not be deleted. Try again." };
  }
  refresh();
  return { ok: true, message: "Idea deleted." };
}
